
#ifndef INTERCEPTOR_DECLARATIONS
#define INTERCEPTOR_DECLARATIONS


#define INTERCEPTOR_NOT_IMPLEMENTED 9999

#define NOT_FOUND 9998

#define ERROR_CHECK_LOGGING

#endif // INTERCEPTOR_DECLARATIONS

